#! /bin/sh

die() {
    echo
    echo "$@"
    exit 1
}


rm -f -f "$HOME/resolv.conf"

curl --fail -sSL https://raw.githubusercontent.com/credfeto/credfeto-setup-arch-vm/refs/heads/main/etc/resolv.conf --output "$HOME/resolv.conf" || die "Could not download DNS"

[ -f "$HOME/resolv.conf" ] || die "resolv.conf not downloaded"

rm -f /etc/resolv.conf

cp -f "$HOME/resolv.conf" /etc/resolv.conf