---
- name: Configure Arch Linux VM
  hosts: localhost
  connection: local
  become: true

  roles:
    - packages
    - users
    - sysctl
    - kernel_modules
    - proc
    - docker
    - grub
    - ssh
    - firewall
    - network
    - apparmor
    - services
    - ansible_pull
