---
- name: Ensure /etc/containers directory exists
  ansible.builtin.file:
    path: /etc/containers
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: container_runtime == 'podman'

- name: Configure Podman registries
  ansible.builtin.copy:
    src: registries.conf
    dest: /etc/containers/registries.conf
    owner: root
    group: root
    mode: "0644"
  when: container_runtime == 'podman'

- name: Enable kernel.unprivileged_userns_clone for Podman rootless containers
  ansible.posix.sysctl:
    name: kernel.unprivileged_userns_clone
    value: "1"
    sysctl_file: /etc/sysctl.d/10-kernel.unprivileged_userns_clone.conf
    reload: true
  when: container_runtime == 'podman'
