---
- name: Ensure /etc/containers directory exists
  ansible.builtin.file:
    path: /etc/containers
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: container_runtime == 'podman'

- name: Configure Podman registries
  ansible.builtin.copy:
    src: registries.conf
    dest: /etc/containers/registries.conf
    owner: root
    group: root
    mode: "0644"
  when: container_runtime == 'podman'
